security:
    enable_authenticator_manager: true
   
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
   
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
   
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|uploads)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator
            logout:
                path: app_logout
                target: /
           
            remember_me:
                secret: '%kernel.secret%'    # required
                lifetime: 604800            # 1 week in seconds
                remember_me_parameter: _remember_me  # Changed this line
                always_remember_me: false
                signature_properties: [password]
   
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
   
    access_control:
        # Public routes
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }
        - { path: ^/uploads/products/, roles: PUBLIC_ACCESS }  # Allow public access to product images
       
        # Admin routes
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/product/new$, roles: ROLE_ADMIN }
        - { path: ^/product/[0-9]+/edit$, roles: ROLE_ADMIN }
        - { path: ^/product/[0-9]+$, methods: [DELETE, POST], roles: ROLE_ADMIN }
       
        # Product routes
        - { path: ^/product$, roles: PUBLIC_ACCESS }
        - { path: ^/product/[0-9]+$, methods: [GET], roles: PUBLIC_ACCESS }
        - { path: ^/product/[0-9]+/customize$, roles: ROLE_USER }
       
        # Cart and order routes
        - { path: ^/cart, roles: [ROLE_USER, '!ROLE_ADMIN'] }
        - { path: ^/order, roles: ROLE_USER }
        - { path: ^/order/confirmation/, roles: ROLE_USER }
       
        # Customization routes
        - { path: ^/customize, roles: ROLE_USER }
       
        # Default secure everything else
        - { path: ^/, roles: ROLE_USER }