[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev"

[deploy]
startCommand = "php bin/console server:start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[build.args]
PHP_VERSION = "8.2"